### ISSUE TITLE
Possible issue with duplicate imagePullSecret patching in updating AMP configurations

### ISSUE THREAD

**Issue by wangeguo** [amphitheatre-app/amphitheatre#3]
When updating `amp-configurations`, if the imagePullSecret is repeatedly patched into the service account without de-duplication, it could cause duplicate credentials in the imagePullSecrets list of the service account. This could potentially result in issues when using these credentials. It is recommended to check if the imagePullSecret already exists in the service account before patching it again, and remove it if it does, in order to avoid duplicate additions and ensure the correctness and reliability of the configuration.

An example of an excerpted ServiceAccount: amp-controllers is as follows:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-controllers
  namespace: amp-system
  labels:
    helm.sh/chart: amphitheatre-0.4.36
imagePullSecrets:
  - name: amp-registry-credentials
  - name: amp-registry-credentials
secrets:
  - name: amp-registry-credentials
  - name: amp-registry-credentials
```
